Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -15,5 +15,10 @@ jobs:
           for url in "${urls[@]}"
           do
             status_code=$(curl -o /dev/null -s -w "%{http_code}\n" $url)
-            echo "$url - $status_code"
+            exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              echo "Error: Failed to check status code for $url"
+            else
+              echo "$url - $status_code"
+            fi
           done
